### ISSUE TITLE
Use the Meson build system

### ISSUE THREAD

**Issue by tshikaboom** [tshikaboom/libone#4]
This would get us rid of a lot of autotools-based stuff, and would (I guess) simplify the project.

**Comment by blu-base** [comment]
Hi Oskar,
though still learning, i have started to rewrite the config scrips for meson.

Could you (briefly) explain the current options regarding Windows? I cannot test them myself.

In `configure.ac`
```Makefile
  # ==========================
  # Platform check for windows
  # ==========================
  AC_MSG_CHECKING([for native Win32])
  AS_CASE([$host],
      [*-*-mingw*], [
          native_win32=yes
          LIBONE_WIN32_RESOURCE=libone-win32res.lo
          ONE2RAW_WIN32_RESOURCE=one2raw-win32res.lo ONE2SVG_WIN32_RESOURCE=one2svg-win32res.lo 
      ], [
          native_win32=no
          LIBONE_WIN32_RESOURCE=
          ONE2RAW_WIN32_RESOURCE= ONE2SVG_WIN32_RESOURCE= 
      ]   
  )
```
Meson can prepare shared and static libraries without libtool, as far as i learned, do you think creating intermittent library objects is still necessary?

In `src/lib/Makefile.am`
```Makefile
if OS_WIN32

@LIBONE_WIN32_RESOURCE@ : libone.rc $(libone_@ONE_MAJOR_VERSION@_@ONE_MINOR_VERSION@_la_OBJECTS)
chmod +x $(top_srcdir)/build/win32/*compile-resource
WINDRES=@WINDRES@ $(top_srcdir)/build/win32/lt-compile-resource libone.rc @LIBONE_WIN32_RESOURCE@

endif
```
I haven't fully understood what `libone.rc` does in this context. Meson seems to be able to create such `.rc` similar to the above snippet. But is it needed for windows (and only for windows)?

**Comment by tshikaboom** [comment]
Hey, that issue was more exploratory than anything else :)

Getting rid of `libtool` is in my experience a good thing, as it makes us jump through some extra hoops when debugging the library with gdb.
I haven't actually compiled the code on a Windows machine so far, but I'll get out my VM and set it up when I get the time, and get back some results. The baseline of functionality would be to get `src/conv/one2svg` or `src/conv/one2raw` successfully running, as that is all we have at this point, so don't feel too conservative functionality-wise, as the scope is not too large.

Not a build system expert either :) So I can't actually review the meat of what's cooking in your branch (as I wanted to learn Meson too). But we'll get there one day!

If that may be of interest, the creator of Meson has tried porting LibreOffice to the build system, to see if that's practically doable, he's done a series of 5 blog posts on this: https://nibblestew.blogspot.com/2020/02/building-very-small-subset-of.html
This is more for the sake of curiosity than anything else, as LO's scope is hundreds of times bigger than what we're trying to do here.

**Comment by blu-base** [comment]
> https://nibblestew.blogspot.com/2020/02/building-very-small-subset-of.html
This is more for the sake of curiosity than anything else, as LO's scope is hundreds of times bigger than what we're trying to do here.

Awesome, thanks!

> I haven't actually compiled the code on a Windows machine so far, but I'll get out my VM and set it up when I get the time, and get back some results. The baseline of functionality would be to get src/conv/one2svg or src/conv/one2raw successfully running, as that is all we have at this point, so don't feel too conservative functionality-wise, as the scope is not too large.

I see. I had the impression that you were developing on windows. That's why i asked. 
Since, it's not the case, I would assume lower priority for non-linux systems for now.

> Not a build system expert either :) So I can't actually review the meat of what's cooking in your branch (as I wanted to learn Meson too). But we'll get there one day!

I'll open a PR when it's good enough to discuss; there is still a lot missing right now...
